### ISSUE TITLE
shinyapps.io

### ISSUE THREAD

**Issue by dcooley** [greghuang8/Geovis#1]
I found your [blog post](https://spatial.blog.ryerson.ca/author/gregory-huang/) on mapdeck and was intrigued by this statement

> Unfortunately, I was unable to successfully publish a live version of the shiny app, as mapdeck is not supported by the shinyapps.io interface.

I've published a few maps on shinyapps.io and was wondering what you meant when you say it isn't supported. Do you get any specific errors when you upload the maps? 

If you want me to help uploading it let me know.

**Comment by greghuang8** [comment]
Hi David! Thanks for reading the blog post. So the error message thrown is this:
![Untitled](https://user-images.githubusercontent.com/32523439/70111755-38bf1480-1621-11ea-83bb-de859f57e307.png)
I didn't really have time back then to really look into it so I thought it might be an issue with mapdeck not being installed properly with shinyapps. I had another look just now and looks like there were masking issues if I force install shiny and mapdeck everytime app.R runs. I've since added conditions to installing packages and it worked! Thanks for raising the issue. The app if you're still interested in seeing it is here: https://greghuang8.shinyapps.io/geovis/

**Comment by dcooley** [comment]
glad you got it working :+1: 
That base map colour scheme is really nice, I might start using it!

**Comment by greghuang8** [comment]
It is indeed - quite a bit of interesting ones up on mapbox. This is a very nice package you made too, super cool to see mapbox being run in the R environment!
